---
version: "2"

services:
    app:
        build: .
        environment:
            - DEPLOY_MODE=prod
        volumes:
            - .:/code
        depends_on:
            - mongodb
        ports:
            # maps container port to host port (VM), which maps to some port on your mac
            - "9090:9090"
        
    mongodb:
        image: mongo:latest
        command: --smallfiles
        ports:
            # maps container port to host port (VM), which maps to some port on your mac
            - 27017:27017
